name: 'List Branches'
description: 'List GitHub Branches using API'
inputs:
  repos:  # id of input
    description: 'YOUR_GITHUB_REPOS'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repos }}
