name: 'List Branches'
description: 'List GitHub Branches using API'
inputs:
  myInput:
    description: "Input to use"
    default: "world"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
